# version: "3.8"

services:
  pyspark:
    build: .  
    container_name: pyspark
    ports:
      - "8888:8888"
    restart: unless-stopped
    volumes:
      - ./work:/home/jovyan/work  
    command: start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''
